config/routes.rb
Wtfmom2::Application.routes.draw do
  root :to => "gifts#random"

  match 'clicks' => 'clicks#create'

end

app/models/gift.rb
class Gift < ActiveRecord::Base
  attr_accessible :name, :url, :price
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  def index
    @gifts = Gift.all
  end

  def random
    @cheap = params[:cheapbastard]

    if @cheap && (@cheap.to_i <= 12) # minimum cheapness
      @incrediblycheap = true      # change link to raise price rather than lower
      @cheap = 12                   # set cheapness to 11 dollars
    end

    @cheap = 500 unless @cheap

    @gift = Gift.find :first, :order => "RANDOM() DESC", 
                      :conditions => ["price <= ?", @cheap.to_i * 100]

    @cheap = nil if @cheap == 500 # Want empty link
  end

  def show
    @gift = Gift.find(params[:id])
  end

  def new
    @gift = Gift.new
  end

  def create
    @gift = Gift.new(params[:gift]) # TODO: comment out or authenticate
    if @gift.save
      redirect_to @gift, :notice => "Successfully created gift." # Taunt
    else
      render :action => 'new'
    end
  end

  def edit
    @gift = Gift.find(params[:id])
  end

  def update
    @gift = Gift.find(params[:id])
    if @gift.update_attributes(params[:gift]) # TODO: comment out / auth
      redirect_to @gift, :notice  => "Successfully updated gift." # Taunt
    else
      render :action => 'edit'
    end
  end

  def destroy
    @gift = Gift.find(params[:id])
    @gift.destroy # TODO: comment out or authenticate
    redirect_to gifts_url, :notice => "Successfully destroyed gift." # Taunt
  end
end

app/helpers/gifts_helper.rb
module GiftsHelper
  def randomize(*arr)
    if (arr.length == 0)
      return 0
    end
    return arr[rand(arr.length)]
  end

  def current_url(overwrite={})
    url_for :only_path => false, :params => params.merge(overwrite)
  end

  def session_increment
    if session[:count]
      session[:count] += 1
    else
      session[:count] = 0
    end
  end

  def sc
    session[:count].to_i
  end

  def save_referer
    unless session['referer']
      session['referer'] = request.env["HTTP_REFERER"] || 'none'
    end
  end

  def ref
    if session['referer']
       session['referer']
    else
      "nowhere"
    end
  end
    

end

app/views/gifts/_form.html.erb
<%= form_for @gift do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/gifts/edit.html.erb
<% title "Edit Gift" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @gift %> |
  <%= link_to "View All", gifts_path %>
</p>

app/views/gifts/index.html.erb
<% title "Gifts" %>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Price</th>
  </tr>
  <% for gift in @gifts %>
    <tr>
      <td><%= gift.name %></td>
      <td><%= gift.url %></td>
      <td><%= gift.price %></td>
      <td><%= link_to "Show", gift %></td>
      <td><%= link_to "Edit", edit_gift_path(gift) %></td>
      <td><%= link_to "Destroy", gift, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Gift", new_gift_path %></p>

app/views/gifts/new.html.erb
<% title "New Gift" %>

<%= render 'form' %>

<p><%= link_to "Back to List", gifts_path %></p>

app/views/gifts/random.html.erb
<p>
<%=
randomize( "WHAT IF YOU FUCKING GOT HER",
"IF YOU LOVED HER YOU'D HAVE ALREADY GOTTEN HER",
"SHE'D FUCKING LOVE",
"CAN YOU FUCKING IMAGINE HER RECEIVING",
"SHE MIGHT UN-DISOWN YOU FOR")
%> </p> <p> <a href="<%= @gift.url %>" target="_new">
  <%= @gift.name %>
</a>
</p>

<% session[:fuck] = "yeah" %>

<% 
   session[:fuck] = "no" if (params[:fuck] == "no")
   if (params[:fuck] == "yeah" || session[:fuck] == "yeah") 
     session[:fuck] = "yeah"
 %>
  <div id="f7u12"> <img src="
  <%= randomize(
  "images/c1.png",
  "images/c2.png",
  "images/c3.png",
  "images/c4.png",
  "images/c5.png",
  "images/c6.png",
  "images/c7.png",
  "images/c8.png",
  "images/c9.png",
  "images/c0.png")
  %>" width="125" />
</div>
<% end %>

<div id="poker">
  <a href="/?fuck=<%= (session[:fuck] == "yeah") ? 'no' : 'yeah'  %>">
    <img src="images/<%= (sc > 3 and sc < 7 and session[:fuck] != "yeah") ? randomize('poker2.png', 'poker3.png', 'poker4.png') : 'poker.png'  %>" height="100" border=0/>
   </a>
</div>

<div id="choices"> 

   <p> <a href="/<%= "?cheapbastard=#{@cheap}" if @cheap %>">
    SHE WON'T FUCKING LIKE THAT.
<%
randomize(
"SHE WON'T FUCKING LIKE THAT.",
"SHE'LL FUCKING HATE IT.",
"I'D RATHER SEE GRANDMA NAKED IN THE SHOWER."
)
%>
</a></p>
<p>
<% if @incrediblycheap %>
  <a href="/">ONLY <%= (@gift.price.to_f / 100).truncate %> DOLLARS? SHE'S MY FUCKING MOTHER!</a>
<% else %>
<a href="/?cheapbastard=<%= @gift.price / 100 %>">
LOVE HER, BUT  <%= (@gift.price.to_f / 100).truncate %> DOLLARS IS TOO FUCKING MUCH.
</a>
<% end %>
</p>
<br>
</div>

app/views/gifts/show.html.erb
<% title "Gift" %>

<p>
  <strong>Name:</strong>
  <%= @gift.name %>
</p>
<p>
  <strong>Url:</strong>
  <%= @gift.url %>
</p>
<p>
  <strong>Price:</strong>
  <%= @gift.price %>
</p>

<p>
  <%= link_to "Edit", edit_gift_path(@gift) %> |
  <%= link_to "Destroy", @gift, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", gifts_path %>
</p>